import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CakeRedux from '@/src/components/CakeRedux'
import IceRedux from '@/src/components/IceRedux'
import { Provider } from 'react-redux'
import store from '@/src/redux/store'
import NewCakeContainer from '@/src/components/NewCakeContainer'
import WalletButton from '@/src/components/WalletButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <div className='w-full h-screen d-flex flex-row justify-center items-center'>
          {/* <IceRedux />
          <NewCakeContainer />
          <CakeRedux /> */}
          <WalletButton />
        </div>
      </Provider>

    </>
  )
}
